### ISSUE TITLE
Adding a 404 error page

### ISSUE THREAD

**Issue by Deepanshu0703** [PradyumnaKrishna/enigma-protocol#61]
Adding a customised 404 error page

**Comment by ydv-ankit** [comment]
duplicate !!
check issue #46

**Comment by Deepanshu0703** [comment]
Hey @ydv-ankit can you assign that issue to me as it is inactive since 2 weeks

**Comment by PradyumnaKrishna** [comment]
I guess adding 404 page in vue.js is not possible. There is a issue in github-pages with vue-router, that makes it not possible.

If you see router of vue.js client I used 
https://github.com/PradyumnaKrishna/enigma-protocol/blob/d52b94eb38f8a7f6673d89f8cfd838f93dc52acb/client/src/router/index.js#L23
because standard routing was leading to error not found.

This makes the url with `#`, so I guess if you add a 404 it simply not work because the url will be `#/404`.

Please do some research and give me a POC of github pages and vue-router, then I will assign it to you.

**Comment by PradyumnaKrishna** [comment]
I am thinking to rebuild the whole client, maybe you have a better alternative. Can you provide me better alternative than vue.js to build the chat app. I am ok with any frontend but keep in mind that I am looking for github pages for deployment.

**Comment by ydv-ankit** [comment]
Isn't react or angular good choice??

**Comment by iditocommerce** [comment]
i added page for error handling. please check it.
